### ISSUE TITLE
Suggestion: API

### ISSUE THREAD

**Issue by ProtoCh4os** [nerdydrew/Random-Pokemon-Generator#3]
Possibly make a RestFul API to get a random Pokemon

**Comment by Blackstareye** [comment]
I am working on a solution.

The issue is, that there is no backend at all so far, because it was intended as a standalone little js application (as far as I can see that).

If the owner allows to have a backend like nodejs, I will include that in my pull request :) 
I saw, that the webpage is located on a aws. Does AWS allow nodejs ?

**Comment by nerdydrew** [comment]
I host Random Pokémon Generator as a static website (front-end only) on Amazon S3. I originally used a back-end server, but that was getting expensive as my site received more traffic. I don't mind if someone else hosts the API, but I'd rather not host it myself.

**Comment by Blackstareye** [comment]
@nerdydrew 

I see. If it is okay from your side, I would run a few tests  and if it is still also usuable as a static website (without api), is it okay, to merge the REST API into your project as well ?

**Comment by nerdydrew** [comment]
I'd rather not so that I don't have to maintain it.

**Comment by Blackstareye** [comment]
@nerdydrew  Understandable.

Then I would maintain the fork with the REST API.
Would you mind, adding a little note to your readme, that the API Part is on that fork?

And Thanks for your quick response.

**Comment by nerdydrew** [comment]
Sure, I just added a link to the README.
